on: 
  push:
    branches:
      - aurora
  # allows to run the job at any time manually
  workflow_dispatch:
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/aurora'
    steps:
      - name: 'checkout'
        uses: actions/checkout@v4.2.2
      - name: 'build and deploy to github pages'
        uses: shalzz/zola-deploy-action@v0.17.2
        env:
          PAGES_BRANCH: aurora
          BUILD_DIR: .
          TOKEN: ${{ secrets.TOKEN }}
          REPOSITORY: 0x61nas/0x61nas.github.io
